
<h1>Article list</h1>
<table>
<?php foreach ($articles as $article) : ?>
        <tr>
            <td>
                <h2><a href="article/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2>
                <?= $article['description'] ?>
                <?php if ($admin) : ?>
                    <br />
                    <a href="editor/<?= $article['url'] ?>">Edit</a>
                    <a href="article/<?= $article['url'] ?>/remove">Remove</a>
                <?php endif ?>
            </td>
        </tr>
<?php endforeach ?>
</table>