<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <link rel="stylesheet" href="style.css" type="text/css"/>
</head>

<body>
<header>
    <h1>MVC practice</h1>
</header>

<?php foreach ($messages as $message) : ?>
    <p class="message"><?= $message ?></p>
<?php endforeach ?>

<nav>
    <ul>
        <li><a href="administration">Home</a></li>
        <li><a href="register">Sign up</a></li>
        <li><a href="login">Login</a></li>
    </ul>
</nav>
<br clear="both" />

<article>
<?php $this->controller->renderView(); ?>
</article>

<footer>

</footer>
</body>
</html>