<h1>Register</h1>

<form method="post">
    Name<br />
    <input type="text" name="name" required/><br />
    Surname<br />
    <input type="text" name="surname" required/><br />
    Email<br />
    <input type="email" name="email" required/><br />
    Date of Birth<br />
    <input type="date" name="birthday" required/><br />
    Password<br />
    <input type="password" name="password" required/><br />
    Password repeat<br />
    <input type="password" name="password_repeat" required/><br />
    Enter the current year (antispam)<br />
    <input type="text" name="abc" /><br />
    <input type="submit" value="Register" />
</form>